#!/bin/bash
# Build "/Applications/Pysar.app" — a Dock-less menu-bar launcher that
# starts the whisper server and the app with one click (Spotlight/Launchpad).
# Also installs a `cream` shell alias. Idempotent: safe to re-run.
#
# Everything it needs lives in the repo, so a fresh Mac just does:
#   make setup && make app
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="/Applications/Pysar.app"
ICNS="$ROOT/assets/Pysar.icns"

echo "📦 Installing $APP (repo: $ROOT)"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ── Info.plist (LSUIElement = menu-bar agent, no Dock icon) ───────────────────
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>Pysar</string>
    <key>CFBundleDisplayName</key><string>Pysar</string>
    <key>CFBundleIdentifier</key><string>com.steptonite.pysar</string>
    <key>CFBundleExecutable</key><string>pysar</string>
    <key>CFBundleIconFile</key><string>Pysar</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleVersion</key><string>1.0</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>LSMinimumSystemVersion</key><string>12.0</string>
    <key>LSUIElement</key><true/>
    <key>NSMicrophoneUsageDescription</key><string>Pysar records your voice locally to transcribe it into text.</string>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# ── Launcher (bakes in this repo's absolute path) ─────────────────────────────
cat > "$APP/Contents/MacOS/pysar" <<LAUNCHER
#!/bin/bash
# Auto-generated by scripts/install_app.sh — do not edit here; edit the repo.
ROOT="$ROOT"
if [ ! -f "\$ROOT/scripts/start.sh" ]; then
    osascript -e 'display alert "Pysar" message "Project not found at $ROOT. Re-run make setup there."'
    exit 1
fi
exec /bin/bash "\$ROOT/scripts/start.sh" >>"\$HOME/Library/Logs/pysar.log" 2>&1
LAUNCHER
chmod +x "$APP/Contents/MacOS/pysar"

# ── Icon ──────────────────────────────────────────────────────────────────────
if [ -f "$ICNS" ]; then
    cp "$ICNS" "$APP/Contents/Resources/Pysar.icns"
else
    echo "⚠️  $ICNS missing — app will use the generic icon. Run: make icon"
fi

# ── Register + refresh icon cache ─────────────────────────────────────────────
plutil -lint "$APP/Contents/Info.plist" >/dev/null
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
[ -x "$LSREGISTER" ] && "$LSREGISTER" -f "$APP" || true
touch "$APP"

# ── `cream` alias (launch from any terminal) ──────────────────────────────────
ZRC="$HOME/.zshrc"
if ! grep -q "alias cream=" "$ZRC" 2>/dev/null; then
    printf '\n# Pysar voice dictation\nalias cream="make -C %s up"\n' "$ROOT" >> "$ZRC"
    echo "🔗 added 'cream' alias to ~/.zshrc"
fi

echo "✅ Done. Launch via Spotlight → “Pysar”, or run 'cream' in a new terminal."
echo "   First run: grant Input Monitoring + Accessibility to Pysar in System Settings."
